### ISSUE TITLE
just some wildcard domains to help against youtube ads a bit

### ISSUE THREAD

**Issue by deathbybandaid** [IAreKyleW00t/pi-hole-lists#1]
## youtube ads

k.googlevideo.com
z.googlevideo.com
7.googlevideo.com
s.googlevideo.com
e.googlevideo.com
r.googlevideo.com
d.googlevideo.com
y.googlevideo.com
6.googlevideo.com
l.googlevideo.com

**Comment by IAreKyleW00t** [comment]
Great! I'll test these out for a bit and see if there are any issues.

**Comment by IAreKyleW00t** [comment]
Unfortunately, the format for YouTube's ad domains cannot be blocked using wildcards, only exact matches. If `dnsmasq` supported regex then this would work.

For example `r.googlevideos.com` (wildcard) would block `*.r.googlevideos.com`, not domains that contain it. So `r6---sn-4g57kndr.googlevideo.com` would be allowed through unless it was explicitly blocked.
